[program:colonizer-hw]
directory=/app/Colonizer
command=/app/Colonizer/venv/bin/python3 -m hwlayer.server
user=colonizer
autostart=true
autorestart=true
#“Wait 20 seconds before deciding whether the program started successfully
# This gives the hardware initialization enough time to complete before Supervisor starts judging success/failure
startsecs=20
stderr_logfile=/var/log/colonizer-hw.err.log
stdout_logfile=/var/log/colonizer-hw.out.log
environment=HOME="/home/colonizer",USER="colonizer",SUDO_HOME="",HARDWARE_TRANSPORT="tcp",SETTLEPLATE_CONFIG="kubernetes"
