ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Username NVARCHAR (32);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Barcode VARCHAR (128);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Lot_no VARCHAR (64);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Version VARCHAR (32);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Location NVARCHAR (128);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Batch NVARCHAR (128);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Colonies VARCHAR (MAX);