ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Username VARCHAR (32);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Barcode VARCHAR (256);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Lot_no VARCHAR (128);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Version VARCHAR (32);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Location VARCHAR (128);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Batch VARCHAR (128);
ALTER TABLE dbo.SETTLEPLATE ALTER COLUMN Colonies VARCHAR (MAX);