[program:colonizer-app]
directory=/app/Colonizer
;allow the environment to control SETTLEPLATE_CONFIG value, if not provided it will be set to "default"
;environment=SETTLEPLATE_CONFIG="production"
command=/app/Colonizer/venv/bin/gunicorn -c gunicorn_config.py webdaemon:app
user=colonizer
autostart=true
autorestart=true
stderr_logfile=/var/log/colonizer-app.err.log
stdout_logfile=/var/log/colonizer-app.out.log
